### PR TITLE
Issue #50 - repos update leaves lock

### LINKED ISSUE #50: Repo update failed and killed git processes, leaving lock files
While the assets compiler was running in the main repo, I attempted to update a repo with several parent repos. The update failed with this message:

```
csemrau@CFNB-0033 MINGW64 /c/dev/cplace/repos/cplace-daimler-ptm (release/5.2)
$ cplace-cli repos -u --force
[CPLACE-CFACTORY-MOCKUPS]: No node_modules folder
[CPLACE-PROJECT-PLANNING-API]: No node_modules folder
[CPLACE-OIDC]: No node_modules folder
working copy of repo cplace-cfactory-deprecated-board is not clean; continue due to force flag
[CPLACE-CFACTORY-DEPRECATED-BOARD]: No node_modules folder
[CPLACE-PROJECT-PLANNING]: No node_modules folder
working copy of repo main is not clean; continue due to force flag
[MAIN]: Moving node_modules to __node_modules
Could not execute given command:
         EPERM: operation not permitted, rename 'C:\dev\cplace\repos\main\node_modules' -> 'C:\dev\cplace\repos\main\__node_modules'
```

I stopped the assets compiler and retried, with this result:

```
csemrau@CFNB-0033 MINGW64 /c/dev/cplace/repos/cplace-daimler-ptm (release/5.2)
$ cplace-cli repos -u --force
[CPLACE-OIDC]: No node_modules folder
[CPLACE-PROJECT-PLANNING-API]: No node_modules folder
[CPLACE-PROJECT-PLANNING]: No node_modules folder
fatal: Unable to create 'C:/dev/cplace/repos/cplace-project-planning/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Could not execute given command:
         undefined
```

Several of the repositories to be updated now had an `index.lock` file. No git process was running anymore.

I guess we need to handle errors in cplace-cli a bit differently, especially we need to let git processes run to completion before aborting the node process.

### PR DESCRIPTION
**Pull request by csemrau**
Fixes #50 

`changelog: Fix git locks left behind when repos -u aborts due to unclean working copy [Issue cplace-npm-tools#50, PR cplace-npm-tools#57]`

### CODE REVIEW

File: src/commands/repos/AbstractReposCommand.ts [hunk 1]
```diff
@@ -27,6 +29,11 @@ export abstract class AbstractReposCommand implements ICommand {
             Global.isVerbose() && console.log('running in force mode');
         }
 
+        this.sequential = !!params[AbstractReposCommand.PARAMETER_SEQUENTIAL];
+        if (this.sequential) {
+            Global.isVerbose() && console.log('running in sequential mode');
```
Comment (csemrau) [inline src/commands/repos/AbstractReposCommand.ts:34]: This option is currently only supported by `repos -u`, and not yet documented in the help text.
How should we proceed here? Should we only document it for that command, or strive to support it in others as well?
I really like the option to run multiple operations sequentially, because it makes the logs tremendously more readable.

File: src/commands/repos/UpdateRepos.ts [hunk 2]
```diff
@@ -17,9 +18,22 @@ export class UpdateRepos extends AbstractReposCommand {
     protected resetToRemote: boolean;
 
     public async execute(): Promise<void> {
-        await Promise.all(
-            Object.keys(this.parentRepos).map((repoName) => this.handleRepo(repoName))
-        );
+        Global.isVerbose() && console.log('update repos - prepare');
+        await promiseAllSettled(
+            {
+                keys: Object.keys(this.parentRepos),
```
Comment (csemrau) [inline src/commands/repos/UpdateRepos.ts:24]: Style: Where should be the line-breaks and what should the indentation be?
When the object braces are on the same line as the parenthesis (`await promiseAllSettled({`), the whole object body is automatically indented quite deep, and I don't really like that.

Comment (stefancplace) [reply src/commands/repos/UpdateRepos.ts:24]: I am ok with the indentation and also happy if we can use autoformat in Intellij

File: src/commands/repos/AbstractReposCommand.ts (hunk 1 above)
Comment (stefancplace) [reply src/commands/repos/AbstractReposCommand.ts:34]: I guess the motiviation of asynchronous workloads was to have better performance. Is there a significant impact on performance?
I am hardly ever using this functionality so I cant tell if it`s worth the effort making this feature available for all commands. Also I am still hoping that dependency management might be done by gradle in the near future. 
I guess it would be a good idea to officially document this feature in cli.ts.

Comment (csemrau) [reply src/commands/repos/AbstractReposCommand.ts:34]: Doing these operations in parallel is much faster, so it should be the default. As said, understanding the logs is much harder when multiple operations are logging in parallel, so I'd like to have a sequential run option in cases something goes wrong.
I will document that the sequential option is available for the repos -u command only.

I have rarely used this command (repos -u) mainly due to its issues, like this one or that it shuffles the node_modules folder around when it is not necessary.
The need to prepare parent repos is very common when you work with another product repo, so this tool is important. Even when master is ready to depend on pre-compiled artifacts, older releases still need this. And as we have seen from some customers, they may lag a year behind and still need bugfixes for their old release.

Comment (stefancplace) [reply src/commands/repos/AbstractReposCommand.ts:34]: Regarding shuffling node_modules do we need to fix this https://github.com/collaborationFactory/cplace-npm-tools/issues/43 ?

Comment (stefancplace) [reply src/commands/repos/AbstractReposCommand.ts:34]: Or should we just remove node_modules handling from cplace-cli in general and advise the developper to manually to an `npm install` if needed?

Comment (csemrau) [reply src/commands/repos/AbstractReposCommand.ts:34]: I will try to understand what is currently happening w.r.t. the node_modules (from the sources and the observations in #43) and what a suitable improvement would be. But not today.

I saw you started working on it, in branch `bugfix/improve-handling-of-node-modules`. :-)

Comment (stefancplace) [reply src/commands/repos/AbstractReposCommand.ts:34]: It would also be possible to do `npm install` anytime on releases >4.57. This takes about 2 additional seconds in case it was not necessary. It might also be an option to do `npm install` in cplace-asc anytime it is started on release >4.57.
